'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'
'     对此文件的更改可能导致不正确的行为，并且如果
'     重新生成代码，这些更改将丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class Login

    '''<summary>
    '''RegisterHyperLink 控件。
    '''</summary>
    '''<remarks>
    '''自动生成的字段。
    '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
    '''</remarks>
    Protected WithEvents RegisterHyperLink As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''LoginUser 控件。
    '''</summary>
    '''<remarks>
    '''自动生成的字段。
    '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
    '''</remarks>
    Protected WithEvents LoginUser As Global.System.Web.UI.WebControls.Login
End Class
